### ISSUE TITLE
Need more information about the data

### ISSUE THREAD

**Issue by jingsam** [osmlab/osm-qa-tiles#13]
I think the more information about the data should be provided, such as:
1. zoom level
2. the vector tiles have buffer or not. Because I want to do some statistics on osm data, the buffer may lead to incorrect results.For example, if I summary the total length of roads all over the world, the result may be longer than it should be.

**Comment by tyrasd** [comment]
+1 for documenting those details!

In order to get you started, here's the info: 1) zoom level is 12, 2) there's no buffer around individual tiles.

**Comment by mikelmaron** [comment]
PRs welcome on https://github.com/osmlab/osm-qa-tiles/blob/gh-pages/index.html

**Comment by jingsam** [comment]
I have sent a PR #14

**Comment by aaronlidman** [comment]
PR merged.
