### ISSUE TITLE
Certain QA tiles do not contain any data.

### ISSUE THREAD

**Issue by l-r** [osmlab/osm-qa-tiles#17]
Certain tiles seems to be empty, for example:

<img width="1654" alt="screen shot 2016-05-18 at 1 39 55 pm" src="https://cloud.githubusercontent.com/assets/1378612/15374429/372e2ad0-1cff-11e6-984c-d7b7031cdc9c.png">

Confirmed that this issue is not with mbview: `tippecanoe-decode usa.mbtiles 12 654 1582` does not output anything. 

This also seems to happen with other regions: 

<img width="1653" alt="screen shot 2016-05-18 at 1 43 17 pm" src="https://cloud.githubusercontent.com/assets/1378612/15374479/641be3f2-1cff-11e6-8bcd-3770402b9e97.png">

I was able to reproduce this with different tiles pulled this morning and yesterday.

/cc @aaronlidman

**Comment by aaronlidman** [comment]
Looks like these tiles exist in the planet file but not the country level extract. So https://github.com/mapbox/mbtiles-extracts is doing something funny.

**Comment by aaronlidman** [comment]
<img width="1411" alt="screen shot 2016-07-01 at 11 48 13 am" src="https://cloud.githubusercontent.com/assets/58878/16542681/7cc54200-4080-11e6-8d5f-869febafe222.png">

Nick fixed this. Country polygons were too simple.
