### ISSUE TITLE
Add 2017 snapshots to http://osmlab.github.io/osm-qa-tiles/historic.html

### ISSUE THREAD

**Issue by mikelmaron** [osmlab/osm-qa-tiles#20]
@ramyaragupathy @jenningsanderson

**Comment by jenningsanderson** [comment]
:wave: @ramyaragupathy and I are working on 2 things for this: 

1. Increasing resolution from annual to quarterly snapshots for these tilesets
2. Fixing the bloating / duplication of data in the current tilesets.

### Further Discussion / Example of (2)
The current annual snapshots located at http://osmlab.github.io/osm-qa-tiles/historic.html were generated with the `multipolygon` flag set for `minjur` and contain duplicated data: multi-polygons are often represented as both multi-polygons and line strings, and sometimes even polygons. As such, you’ll notice the sizes of the tilesets varies (grows) drastically. As such, data is duplicated / triplicated. 

Example: http://mapbox.github.io/osm-analysis-collab/user-summary?minEdits=1&minPercent=0&userList=[%22PlaneMad%22]&yearIdx=10&#4.21/37.931/-87.070. 
While `PlaneMad` edited a lot in 2015, he didn’t actually edit a feature on every tile inside Indiana, but rather edited the relation that is Indiana, version 117, here: https://osmlab.github.io/osm-deep-history/#/relation/161816. 

The multipolygon that is "Indiana" propagated the single edit to the administrative boundary to every tile contained within. If counting edits, objects, or users with these tilesets, they will be dramatically over-represented by this propagation.

**Comment by jenningsanderson** [comment]
### Further discussion with figures of this issue: 
https://gist.github.com/jenningsanderson/9350924d1a692e631ac72b09ef49a94b

**Comment by jenningsanderson** [comment]
2016-Q4 (2017-01-01) historic snapshot is available here: https://s3.amazonaws.com/mapbox/playground/ramyaragupathy/snapshots/2016-Q4-qa-tiles.mbtiles

@geohacker -- can we find a permanent place for these quarterly snapshots and update http://osmlab.github.io/osm-qa-tiles/historic.html accordingly?

**Comment by planemad** [comment]
TODOS:
- [x] Move files from playground to osm-qa-tiles s3 bucket
- [x] Define what is a historic snapshot and how to use it
- [x] Update links and description http://osmlab.github.io/osm-qa-tiles/historic.html

**Comment by jenningsanderson** [comment]
The historic.html page has been updated: https://osmlab.github.io/osm-qa-tiles/historic.html
