### ISSUE TITLE
The size of osm-qa-tiles decreased from 35GB to 22GB, what's happening?

### ISSUE THREAD

**Issue by jingsam** [osmlab/osm-qa-tiles#3]

**Comment by e-n-f** [comment]
I think you are seeing the result of a change to make the tiles be complete at zoom level 12 instead of continuing to higher zooms.

**Comment by jingsam** [comment]
I'm curious why no longer provides tiles of zoom-15

**Comment by aaronlidman** [comment]
@jingsam - We've found zoom level 12 more optimal for creating the tiles quicker and faster for iterating across the entire word for large scale analysis. Zoom 12 just requires less work.

**Comment by jingsam** [comment]
I plan to make some statistics on OSM. I want ungeneralized data for accuracy. Does zoom 12 is good enough for large scale analysis?

**Comment by aaronlidman** [comment]
Yes @jingsam, al geometries are unsimplified and we use zoom 12 for large scale analysis everyday.
