### ISSUE TITLE
Is a history of these files kept?

### ISSUE THREAD

**Issue by paulmach** [osmlab/osm-qa-tiles#9]
Is there a way to download the file from a month or two ago?  ie. a qa tiles snapshot of osm from some time in history?

**Comment by aaronlidman** [comment]
Not currently. We only keep the previous day and the day before.
- `latest.planet.mbtiles.gz`
- `previous.planet.mbtiles.gz`
- `/latest.country/<all countries>`
- `/previous.country/<all countries>`

We don't have any use for them after that. I've been meaning to blog how we create these so you could create your own. But in short, [minjur](https://github.com/mapbox/minjur) reads an osm pbf and outputs a geojson stream. Tippecanoe accepts a geojson stream and outputs vector tiles.

**Comment by paulmach** [comment]
Cool thanks. I guess if you really wanted it you'd could compute it again from an old pbf files.
